name: Test

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: "Import Certificate: Development"
        uses: devbotsxyz/xcode-import-certificate@master
        with:
          certificate-data: ${{ secrets.DEVELOPMENT_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.DEVELOPMENT_CERTIFICATE_PASSPHRASE }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # - name: Install required build toolchain
      # if: matrix.os == 'ubuntu-latest'
      # run: sudo apt-get install gcc-multilib g++-multilib

      - name: Install dependencies
        run: yarn install --frozen-lockfile && npm install -g electron-builder

      - name: Get commit message
        run: echo "::set-output name=message::$(git log --no-merges -1 --oneline)"

      - name: Does building work?
        run: yarn run build

      - name: build for mac
        run: electron-builder --no-deref-symlinks
        env:
          GITHUB_TOKEN: ${{ github.token }}


      - name: Done
        run: echo Done.
        
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: fifo
          path: ./dist/mac