name: Test

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # - name: Install required build toolchain
      # if: matrix.os == 'ubuntu-latest'
      # run: sudo apt-get install gcc-multilib g++-multilib

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:

      - name: Get commit message
        run: echo "::set-output name=message::$(git log --no-merges -1 --oneline)"

      - name: Does building work?
        run: yarn run build


      - name: Done
        run: echo Done.